const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../static/app.js'), 'utf8');
const context = vm.createContext({Date, Set, console});
vm.runInContext(source.slice(0, source.indexOf('function renderStats()')), context);
context.task = {id:1,status:'running',stage:'wait_new_email_otp',message:'<img src=x onerror=alert(1)>',started_at:'2026-09-20T18:00:00',stage_started_at:'2026-09-20T18:00:30'};
const waiting = vm.runInContext('progressMarkup(task)', context);
assert.match(waiting, /步骤 4 \/ 7/);
assert.equal((waiting.match(/class="done"/g)||[]).length, 3);
assert.equal((waiting.match(/aria-current="step"/g)||[]).length, 1);
assert.match(waiting, /&lt;img/);
assert.doesNotMatch(waiting, /<img/);
context.task = {...context.task,status:'success',stage:'protocol_verified',completed_at:'2026-09-20T18:01:23'};
const success = vm.runInContext('progressMarkup(task)', context);
assert.match(success, /7 \/ 7 已完成/);
assert.match(success, /1 分 23 秒/);
assert.equal((success.match(/class="done"/g)||[]).length, 7);
context.task = {...context.task,status:'failed',stage:'manual_review',stop_requested:true};
assert.equal(vm.runInContext('taskStage(task)',context),'等待核验换绑结果');
context.task = {...context.task,status:'running',stage:'protocol_upstream',stop_requested:false};
assert.doesNotMatch(vm.runInContext('progressMarkup(task)',context), /步骤 \d \/ 7/);
assert.match(vm.runInContext('progressMarkup(task)',context), /等待详细步骤上报/);
context.task = {...context.task,status:'failed',stage:'failed'};
assert.match(vm.runInContext('progressMarkup(task)',context), /未保存分步记录/);
assert.equal(vm.runInContext("duration('invalid')",context),'—');
console.log('Progress UI: stage states, terminal timing, legacy tasks and HTML escaping passed.');
